#ifndef STRINGTHEORY_NATIVE_CONFIG_H
#define STRINGTHEORY_NATIVE_CONFIG_H

#define HAVE_STDLIB_H 1
#define HAVE_STDIO_H 1
#define HAVE_MATH_H 1
#define HAVE_STRING_H 1
#define HAVE_ERRNO_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDARG_H 1
#define HAVE_COMPLEX_H 1
#define HAVE_C99_VARARGS_MACROS 1
#define HAVE_STDINT_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_IMMINTRIN_H 1
#define PACKAGE "libsamplerate"
#define VERSION "0.2.2"

#endif
