<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AlphaTabRenderHelper</AssemblyName>
    <RootNamespace>AlphaTabRenderHelper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AlphaTab.Windows" Version="1.8.2" />
  </ItemGroup>
</Project>
